#UI (Streamlit)

import streamlit as st 
import datetime 
import requests 
import sys 

#port=8000
BASE_URL = "http://localhost:8000"  #backend endpoint

#set configuration
st.set_page_config(
    page_title = "Travel Planner Agent Application",
    page_icon = "🌎",
    layout = "centered",
    initial_sidebar_state = "expanded",
)


st.title("Travel Planner Agentic Application")
    

#initialize chat history
if "messages" not in st.session_state:
    st.session_state.messages = []

st.header("Where you goin'?")

with st.form():
    user_input = st.text_input("User Input", placeholder="Plan a trip to Goa for 5 days.")
    submit_button = st.form_submit_button("Send")

if submit_button and user_input.strip():
    try:
        with st.spinner("Thinking..."):
            payload = {"query": user_input}
            response = requests.post(f"{BASE_URL}/query", json=payload)

        if response.status_code == 200:
            answer = response.json().get("answer", "No answer returned.")
            markdown_content = f"""# AI Travel Plan

            ---

            {answer}

            ---
             
            "This travel plan was generated by AI. Please verify important information." 

            """
        else:
            st.error("Failed to respond: " + response.text) 
    
    except Exception as e:
        raise f"The response failed due to {e}"
    

